name: listflow_music_app
description: Aplicativo de curadoria musical usando a API do Spotify

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e navegação
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296
  
  # Gerenciamento de estado
  provider: ^6.1.1
  
  # Requisições HTTP
  http: ^1.1.0
  
  # Persistência local
  shared_preferences: ^2.2.2
  
  # Utilitários
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  shimmer: ^3.0.0
  flutter_web_auth_2: ^3.0.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - img/logo.png
    - "img/LOGOS (2).png"
    - img/novob.jpeg
    - img/banco.jpeg
    - img/trapbr.jpg
    - img/fdsteto.jpeg
    - img/funk.jpeg
